name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Check Git Version
        run: git --version

      - name: Check Python Version
        run: python --version

      - name: Check Java Version
        run: java --version

      - name: Check Docker Version
        run: docker -v

      - name: Check kubectl Version
        run: kubectl --version
